pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: appRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo “running CI for master”
